mysql:
  host: 127.0.0.1
  port: 3306
  name: myblog
  user: root
  password: 123456#!
  charset : utf8
  prefix : tb_
cache:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
storage:
  accesskey: BpCTd2kff2Zk87K6O7fcL9Kt_KebchzWkVG23DcQ
  secretkey: oJSrEo6sb5CgwHGB_ThxHI3cZdwOWNEoZqjig8xC